import pandas as pd
from IPython.display import clear_output
from googleapiclient.discovery import build
API_KEY = open('google-api-key.txt', 'r').read()
youtube_service = build('youtube', 'v3', developerKey=API_KEY)


def download_channel_videos(channel, max_videos=2000):
    """
    Download metadata for a limited number of videos (e.g., 1000) from the given channel
    from the YouTube API.
    """
    videos = []
    pageToken = None
    while len(videos) < max_videos:  # Fetch until we get the desired number of videos
        response = youtube_service.playlistItems().list(
            playlistId=channel['playlist_id'],
            part="snippet",
            pageToken=pageToken,
            maxResults=50  # Max results per request (50 is the maximum allowed)
        ).execute()

        # Append the videos to the list
        for video in response['items']:
            videos.append({
                'youtube_id': video['snippet']['resourceId']['videoId'],
                'title': video['snippet']['title'],
                'description': video['snippet']['description'],
                'published_at': video['snippet']['publishedAt'],
                'channel_youtube_id': channel['youtube_id'],
            })
        
        # Stop if we have fetched enough videos
        if len(videos) >= max_videos:
            break
        
        # Get the nextPageToken for pagination
        pageToken = response.get("nextPageToken")

        # Print the progress
        clear_output(wait=True)
        print(f'Downloading videos from "{channel["title"]}": {len(videos)}...')

    # Truncate the list to exactly the desired number of videos (if there are more than max_videos)
    return videos[:max_videos]



def download_channels_videos(channels):
    """
    Download metadata for all videos of all the given channels,
    then creates a separate CSV file (named videos-<CHANNEL>.csv)
    with that information for each channel.
    """
    for _, channel in channels.iterrows():
        videos = download_channel_videos(channel)
        df = pd.DataFrame.from_records(videos)
        output_file = 'videos-{}.csv'.format(channel['slug'])
        df.to_csv(output_file, index=False, encoding='utf-8')
        print ("Generated file: %s" % output_file)
        

def merge_channel_videos(channels, output_file='videos-MERGED.csv'):
    """
    Merge all videos-<CHANNEL>.csv files previously generated by
    `download_channels_videos()` into a single videos-MERGED.csv file.
    """
    # Merge all videos together
    videos = []
    for _, channel in channels.iterrows():
        channel_videos = pd.read_csv('videos-%s.csv' % channel['slug'])
        channel_videos['channel'] = channel['title']
        videos.append(channel_videos)
    videos = pd.concat(videos, ignore_index=True)
    videos['description'].fillna('', inplace=True)
    videos.dropna(inplace=True)
    videos.to_csv(output_file, index=False, encoding='utf-8')
    print ("Channel videos merged into %s" % output_file)